name: safe_result
description: A Dart package providing a Result type for handling success and error cases in a type-safe way.
version: 1.1.1
repository: https://github.com/mobpack/safe_result
homepage: https://github.com/mobpack/safe_result

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
